---
version: '3.3'
services:
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag-app
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/wallabag/images:/var/www/wallabag/web/assets/images
      - /var/docker/wallabag/data:/var/www/wallabag/data
    depends_on:
      - wallabag-db
    links:
      - wallabag-db
    environment:
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag-sql
      - SYMFONY__ENV__DATABASE_PASSWORD= #Hier das Passwort von MYSQL_PASSWORD aus dem Datenbankcontainer setzen
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.com #Domain anpassen
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.wallabag-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wallabag-http.entrypoints=web"
      - "traefik.http.routers.wallabag-http.rule=Host(`wallabag.example.com`)" #Domain anpassen
      - "traefik.http.routers.wallabag-http.middlewares=wallabag-https@docker"
      - "traefik.http.routers.wallabag.entrypoints=web-secure"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag. example.com `)" #Domain anpassen
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.http.routers.wallabag.tls.certresolver=default"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

  wallabag-db:
    image: mariadb
    container_name: wallabag-db
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/wallabag/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wallabag
      - MYSQL_USER=wallabag-sql
      - MYSQL_PASSWORD=MeinWallabagPasswort # Starkes Passwort setzen!
      - MYSQL_ROOT_PASSWORD=MeinWallabagRootPasswort # Starkes Passwort setzen!

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
